### PR TITLE
Allow use of sub routes for more granular permissions

### PR DESCRIPTION
**Pull request by nyambati**
#### What does this PR do?
This PR is meant to introduce sub route feature. This will allow subroute definition for more granular permission allocation. It will also use routes to match permission instead of main resource string.

#### Description of Task to be completed?
This PR implements
- Use of sub-routing
- Use off routes instead of resources

#### How should this be manually tested?
This feature can be tested by running `npm test`, or manually through use of the provided example.

#### Any background context you want to provide?
Before we could only specify a resource we need to guard, this means that all the routes that fall under that resource will be subjected to the same permissions. This meant that if any route within the resource could not be further protected. With the new implementation, you can now specify whether the permission should apply to child routes too. This was achieved through use of route matching i.e `/api/user` will match route `/api/user` while `/api/user/*` will match routes with prefix `/api/user`. 
### New configuration
```yml
- group: user
  permissions:
    - resource: users/*
      methods:
        - GET
        - POST
        - DELETE
      action: allow
      subRoutes:
        - resource: public/
          methods:
            - GET
            - POST
            - DELETE
          action: allow
  
```

### CODE REVIEW

**Comment by nyambati** [comment]
@matthewreed26 Can you help me review this changes, I feel like they will be able to provide the functionality you are looking for.

**Comment by matthewreed26** [comment]
Yes, I agree. Just looking over some of the change diffs now!

**Comment by nyambati** [comment]
@matthewreed26 Thanks for the review. Appreciated

**Comment by matthewreed26** [comment]
@nyambati Thanks for your work. Do you know when you'll be merging this PR?

**Comment by nyambati** [comment]
@matthewreed26 Before EOD

**Comment by matthewreed26** [comment]
@nyambati Glad to see the merge! Looking forward to utilizing once the new version is released on npm.

**Pull request merged**
